version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: mix phx.server
    volumes:
      - .:/usr/local/sandbox
    depends_on:
      - db
    environment:
      - MIX_ENV=dev
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sandbox_dev
    ports:
      - 5432:5432
